// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqzYVKK-LNfgXCPxqDXkjDbpMGajnByD8',
    appId: '1:436602863722:web:9ed20c6b283dc3db958a13',
    messagingSenderId: '436602863722',
    projectId: 'safarlink',
    authDomain: 'safarlink.firebaseapp.com',
    storageBucket: 'safarlink.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZtZtQ6GW3-oS-nbdWM1ugrPURRsm_9Vo',
    appId: '1:436602863722:android:bde42d276e1dd198958a13',
    messagingSenderId: '436602863722',
    projectId: 'safarlink',
    storageBucket: 'safarlink.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEC9mUJUYyUywBKCL1NJ_n1eJ4f4wa0Ig',
    appId: '1:436602863722:ios:952f8cbe27b81bb7958a13',
    messagingSenderId: '436602863722',
    projectId: 'safarlink',
    storageBucket: 'safarlink.firebasestorage.app',
    iosBundleId: 'com.example.safarlink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEC9mUJUYyUywBKCL1NJ_n1eJ4f4wa0Ig',
    appId: '1:436602863722:ios:952f8cbe27b81bb7958a13',
    messagingSenderId: '436602863722',
    projectId: 'safarlink',
    storageBucket: 'safarlink.firebasestorage.app',
    iosBundleId: 'com.example.safarlink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqzYVKK-LNfgXCPxqDXkjDbpMGajnByD8',
    appId: '1:436602863722:web:94f1a421b13efb2d958a13',
    messagingSenderId: '436602863722',
    projectId: 'safarlink',
    authDomain: 'safarlink.firebaseapp.com',
    storageBucket: 'safarlink.firebasestorage.app',
  );
}
